// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using interviewer.Data;

#nullable disable

namespace interviewer.Migrations
{
    [DbContext(typeof(InterviewerDbContext))]
    [Migration("20230904033056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "46e00514-0e07-41da-a30f-225a262c97a7",
                            ConcurrencyStamp = "f53ceaeb-a692-4b7a-ab4d-32c0a8a60efa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "87dcc9dd-ddb8-4d05-83bc-82cfe62b019f",
                            ConcurrencyStamp = "63f46139-939b-49d6-a159-5594d14a67cf",
                            Name = "Interviewer",
                            NormalizedName = "INTERVIEWER"
                        },
                        new
                        {
                            Id = "123e1f3b-df90-481b-9888-cbc701878782",
                            ConcurrencyStamp = "605017f2-d995-4cdf-91b7-b6de11a02b95",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Comment", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepId")
                        .HasColumnType("int");

                    b.Property<string>("InterviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("interviewer.Data.Interviewer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("interviewer.Data.InterviewerUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("interviewer.Data.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondDepartment")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "68ddd41e-0b37-483a-ac01-637d9ad31184",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "8e8e8907-609a-49cd-bb86-4a199c237a6e",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "dbaeeeef-7f2b-494d-a6db-24589ca032ab",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "83e882b1-e56a-4274-8092-e98173fa8f37",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "654e0f39-8ee0-4af4-b7ff-80c413b81ceb",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "22b8334f-1e98-4597-8f9f-1ac71c081735",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "53944bed-13d7-477d-b39c-f3518867026e",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "630eba5e-39ad-4a98-9407-f9b9d626ce35",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "223a65a7-ff08-4ad7-910a-1f5b555ced3c",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c1fec9e3-4f28-4d33-be4a-f62a9eec68c3",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "7262b128-640d-4fe9-a2a1-aba76614b54a",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "74bc7e0f-747f-4a43-81ed-dd82d6ea1fd6",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "667efea3-4429-488b-8f90-a9e5dec47ed9",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "ac74cb67-de19-47e4-9660-08e70e7219fc",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "3720bdc2-1b34-4612-af08-c8913679ad46",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "16d1ab7e-1447-47ef-a993-bf101de80793",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "5d2c77b3-1e91-4687-9fae-8fd6bb4cd0b5",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "69b2ace4-5958-4462-bd42-8269db67c0f1",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "1482e87e-667c-41ce-b020-16137d078ab0",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c9f667ec-5ede-4462-903f-1a63c28a4ad0",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "ad2516e4-811d-49ab-88a6-b7d172c8118a",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "6bd88aee-0c32-4e41-b47e-3a54d584faa7",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "d1c243a4-83f8-4152-9075-6f809b2a0580",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "d3b9836d-59af-4ec5-b7bf-328b79229d5d",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "2f199706-280b-465a-88a8-061b404d5669",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "4e026a46-fa66-4c68-b9d2-40826930170c",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c071cee5-5b80-4876-a3d0-6605e1090382",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "49c4240d-3b52-4d9c-9d8f-12290aa5491e",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "7374220c-5109-49e2-bfa1-0c4cdb6960e7",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "1fc6b8c8-fc68-4add-b36b-ac2b0ecc1ec2",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c9a0531c-60e9-48c3-bb10-90ef2d1ec45f",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "98f52159-2a41-4372-b7cd-003b464ebf97",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "44e8c7fc-04ed-4e98-90d1-e6b869123485",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "39f02c2c-abfe-4a42-89d2-2fd582c41ecf",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "0f692f32-3e52-431e-a448-923649648ca8",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "dc263940-1ac8-45f4-b6ba-aa35b946caf1",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "cc5de8ed-300c-4a26-bd0e-0e45b81ef0b1",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "5a22fbf0-8949-4cba-8242-1794013a48d1",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "e7a6a668-4f2d-44a4-b807-aaf9d49983a4",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "4a96c055-a59e-4896-8eaa-59235d8f29ad",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "cb6c5ca1-acdd-4414-9332-67916aa6940d",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "416e4f88-5ef7-4668-853c-1c4b584c68a0",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "8bf4391b-6e72-4a43-955e-cc965727660d",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b9dd7d49-d326-4688-bf9b-969cab3ed630",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "e7313c2b-195a-4c17-bdcc-fe4a4609ed41",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b8368f83-eed7-48ca-bb00-eeb84919fd3f",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "0942e729-6c53-42ed-87ba-308974514e47",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "aa085920-f419-412a-a426-9c7ef3e27a2b",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c48d73b4-9972-43ec-bca5-b257aa22e098",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "19e996e6-0425-4d14-96a1-fe522505c34c",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "0bf4ca9f-a09c-405a-9149-99c76db9d3e2",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "bb189769-1aad-4b49-9e16-5348a188a8a1",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b7bcbe22-adb1-4f36-8db7-f20fbbf34cc8",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "07adf955-4631-4657-8d16-68b962274ef0",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "e99fd37c-a5c8-4cd6-acd2-e8cd109f5173",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "396a3229-3f33-4785-b91a-a8551b64ebfc",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "68aff82f-45b6-4d03-aa4e-b442884ce08b",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "16226bd7-c664-493b-a8af-9f4db1eac528",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "e701e1ff-5cda-4b49-9aa6-ff079ccc4b6b",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "89dbddcb-c436-4dae-a23c-d192b8e7d8e8",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "fdadd46b-15c2-4f26-92e9-a8c70df728dd",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "8da8bb4e-cee6-4abc-a65f-bdc51bf99b07",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "27307c20-a25e-44c5-be24-3b6e4c4085d8",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "61f57a02-f465-4f1f-8ce6-8d3c54804c7b",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "768bfd56-3f62-4b38-8608-4d947bd955db",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "5fd18f66-2751-4ccf-90c9-72175bbdc41a",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "8a1a5631-69af-4d33-8392-5dca1817de0d",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "302dd18c-8bc1-4418-864c-48f52874a1c6",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b7b92175-c0e4-4da3-8a8e-aeb7764d324d",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "5b5dc131-7668-4266-816d-0f1aa2dbf0a9",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "9139f210-c52d-45b7-b751-7d0b07121b26",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "460a9475-e473-46cc-a32e-26deada50ad3",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "842abba3-a355-49c9-b39c-b038d73683b3",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "3471166f-f296-4ef5-a1c8-ec1bc14c73ba",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "32836baf-0bc0-4a33-9924-d2bf28d57151",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "72f8570f-4a39-4511-b703-604bbac6a8f6",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b2786cc4-3d49-454c-84f8-4e7e40e7f80e",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "1af7effb-1d8e-4e45-b67a-bf3782ed82d9",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "bf51feed-650c-46df-832f-39127eb27075",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "511b36f5-01da-4e06-97d2-5bf99d6f4fb8",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "6cb1e10e-3260-4392-af02-f9b188bb1ee9",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "259c8ed6-283f-4f9f-a802-cb847cc7d389",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "233d9d24-9de4-47da-a5a7-f119c0bd7906",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "bab978e9-0bba-443c-b82e-bfe37439ace3",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "ca17f5b5-4cdc-430c-8ec1-dac60ea908ac",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "353455c1-4fda-4090-b266-cc3905ff6c35",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "4ba612ce-37ff-4980-9294-da80f205fdac",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "ee87dffa-aa4f-4f48-a152-6fe845455f64",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "6bd0d6b8-10ff-4f2e-9964-8906c6c086e6",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "3da0252a-6b80-4453-b17e-ebcfe6d49031",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "8bf779ea-1d6a-4ddb-a9e2-ea4d55b66d88",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c61adfea-099a-40ac-8856-d7956b27fb4c",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "64fd8d2e-b750-442f-b817-887b6b34cc16",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "3a692f54-4943-44b2-b420-1cc736dcd642",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "c5982ace-28a5-45dd-8df6-cc49706af664",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "75fc3897-0dd8-4f96-9f18-830183c0dbeb",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "0b4aee17-393d-4756-af33-46c14e8530c0",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "15433eb6-a290-4053-9559-de4f7567e8f8",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "b6d26b67-2a76-477b-b7d4-81f60d0ede73",
                            College = "计算机学院",
                            FirstDepartment = 7,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "HeChu",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        },
                        new
                        {
                            Id = "996e30f1-897a-41c1-8613-98484210bd2c",
                            College = "计算机学院",
                            FirstDepartment = 3,
                            Grade = "22网络工程",
                            Introduction = "学生",
                            Name = "ChuHe",
                            Phone = "13323588435",
                            Qq = "235247902",
                            State = 10,
                            StudentId = "3122004832"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("interviewer.Data.InterviewerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
